"""add_is_new_user

Revision ID: 0c8363644847
Revises: 72b3fdb8edf8
Create Date: 2025-02-03 13:08:39.625366+04:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c8363644847"
down_revision: Union[str, None] = "72b3fdb8edf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("visits", sa.Column("is_new_user", sa.Boolean(), nullable=True))
    op.execute("UPDATE visits SET is_new_user = TRUE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visits", "is_new_user")
    # ### end Alembic commands ###
