"""add_landing_to_visit

Revision ID: 24e39880c9a5
Revises: 0c8363644847
Create Date: 2025-07-14 22:18:12.188998+04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24e39880c9a5'
down_revision: Union[str, None] = '0c8363644847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "visits",
        sa.Column(
            "landing_page",
            sa.String(),
            nullable=True,
            server_default="memovoz.ru"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visits", "landing_page")
    # ### end Alembic commands ###