"""add_preview

Revision ID: 3cd43f8976ba
Revises: 9ef554bff5ef
Create Date: 2025-01-16 23:12:19.523947+04:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cd43f8976ba"
down_revision: Union[str, None] = "9ef554bff5ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memes", sa.Column("preview", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memes", "preview")
    # ### end Alembic commands ###
