"""add_link

Revision ID: 5e52cab7336c
Revises: 6f0c3f50be39
Create Date: 2024-12-13 23:54:28.014124+04:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e52cab7336c"
down_revision: Union[str, None] = "6f0c3f50be39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memes", sa.Column("link", sa.String(), nullable=False))
    op.create_unique_constraint(None, "memes", ["link"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "memes", type_="unique")
    op.drop_column("memes", "link")
    # ### end Alembic commands ###
