"""add labels m2m back populates

Revision ID: 608cc08d8e4c
Revises: 7fff1f4527a0
Create Date: 2024-09-16 09:41:39.974340+04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608cc08d8e4c'
down_revision: Union[str, None] = '7fff1f4527a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
