"""add_ip_to_visit

Revision ID: 72b3fdb8edf8
Revises: 3b9a78529baf
Create Date: 2025-01-26 22:30:05.346578+04:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72b3fdb8edf8"
down_revision: Union[str, None] = "3b9a78529baf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("visits", sa.Column("ip", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visits", "ip")
    # ### end Alembic commands ###
