"""initial_migration2

Revision ID: 88367997b77a
Revises: aa1d5b218a8b
Create Date: 2024-09-02 22:10:48.251829+04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88367997b77a'
down_revision: Union[str, None] = 'aa1d5b218a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('category', postgresql.ENUM('OTHER', 'CATS', 'PEOPLE', name='category_meme_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memes', 'category')
    # ### end Alembic commands ###
