"""add_is_admin

Revision ID: 9742bfbcea59
Revises: 9b5b222c20c8
Create Date: 2024-12-18 21:48:00.482401+04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9742bfbcea59'
down_revision: Union[str, None] = '9b5b222c20c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text("'f'"), nullable=False))
    op.execute("UPDATE users SET is_admin = 'f'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
