"""add_name

Revision ID: 9b5b222c20c8
Revises: 7f21c4828740
Create Date: 2024-12-15 15:02:16.992192+04:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b5b222c20c8"
down_revision: Union[str, None] = "7f21c4828740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memes", sa.Column("name", sa.String(), nullable=False))
    op.alter_column("memes", "source_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("memes", "source_type", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("memes", "source_type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("memes", "source_name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("memes", "name")
    # ### end Alembic commands ###
