"""initial migration5

Revision ID: f3697632dc4b
Revises: a69c625ece84
Create Date: 2024-09-19 11:08:11.654013+04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3697632dc4b'
down_revision: Union[str, None] = 'a69c625ece84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['author_name'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'author_name')
    # ### end Alembic commands ###
