"""initial migration

Revision ID: f7fea55b4c60
Revises: 
Create Date: 2024-08-30 23:09:22.950539+04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fea55b4c60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author', sa.String(), nullable=True))
    op.drop_constraint('messages_author_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'author_id')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('messages', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('messages_author_id_fkey', 'messages', 'users', ['author_id'], ['id'])
    op.drop_column('messages', 'author')
    # ### end Alembic commands ###
