volumes:
  pgdata:
  minio_data:

services:
  frontend:
    build:
      context: ./frontend
    container_name: mems-frontend
    ports:
      - 3000:3000

  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-non-dev
    volumes:
      - pgdata:/var/lib/postgresql/data/

  api:
    build:
      context: ./api
    env_file:
      - .env-non-dev
    container_name: mems-api
    ports:
      - 8000:8000
    depends_on:
      - db
      - s3_storage
    command: sh -c 'poetry run alembic upgrade head &&
                    poetry run gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000'

  s3_storage:
    build:
      context: ./storage
    env_file:
      - .env-non-dev
    container_name: s3-storage-api
    ports:
      - 1234:8888
    depends_on:
      - minio
    command: sh -c 'poetry run gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8888'

  minio:
    container_name: minio
    image: minio/minio
    env_file:
      - .env-non-dev
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - 9000
    volumes:
      - minio_data:/data