name: Code checks

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - run: cd api && poetry install --no-interaction --no-root

      - run: ls
