name: Code checks

on: [push]

env:
  DB_HOST: localhost
  DB_PORT: 5432
  TEST_DB_NAME: mems_test
  DB_USER: postgres
  DB_PASSWORD: postgres

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Run Pytest
        run: |
          ls
          cd api
          poetry install --no-interaction --no-root
          poetry run pytest .

